#! /usr/bin/env bash

# Public domain

export shell_opts="${shell_opts:--u -e -o pipefail}"
set ${shell_opts}

channel="${1}"; shift
message="${1}"; shift

sudo -u overmind ~overmind/msg "${channel}" "${message}"
